{
  "head": {
    "tot_cnt": "18",
    "pub_area_code": "J",
    "pub_country": "JP",
    "pub_city": "OSA",
    "dept_code": "",
    "DY_LIST": "2,3,4,5,6,7,1",
    "page_num": "1",
    "page_len": "20",
    "flatfile_yn": "N"
  },
  "cont": [
    {
      "sort_no": "0",
      "pkg_mst_code": "JOP500",
      "sMonth": "201609",
      "min_amt": "529000",
      "max_amt": "1899000",
      "mst_name": "오사카 3일-전일관광",
      "t_content": "간사이 핵심지역을 돌아보는 오사카 2박3일 패키지상품입니다.",
      "img_seq": "P000164328",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "간사이 핵심지역을 돌아보는 오사카 2박3일 패키지상품입니다.",
      "tour_day": "3",
      "start_dy": "매일",
      "orderSeq": "1"
    },
    {
      "sort_no": "1",
      "pkg_mst_code": "JOP501",
      "sMonth": "201609",
      "min_amt": "479000",
      "max_amt": "1799000",
      "mst_name": "오사카 3일-1일자유",
      "t_content": "1일자유관광이 가능한 2박3일 상품입니다.",
      "img_seq": "P000020712",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "1일자유관광이 가능한 2박3일 상품입니다.",
      "tour_day": "3",
      "start_dy": "매일",
      "orderSeq": "2"
    },
    {
      "sort_no": "2",
      "pkg_mst_code": "JOP505",
      "sMonth": "201609",
      "min_amt": "529000",
      "max_amt": "1899000",
      "mst_name": "오사카 3일-유니버셜 스튜디오(USJ)",
      "t_content": "유니버셜 스튜디오 재팬을 방문하는 2박3일 상품입니다.",
      "img_seq": "P000118587",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "유니버셜 스튜디오 재팬을 방문하는 2박3일 상품입니다.",
      "tour_day": "3",
      "start_dy": "매일",
      "orderSeq": "3"
    },
    {
      "sort_no": "3",
      "pkg_mst_code": "JOP511",
      "sMonth": "201609",
      "min_amt": "649000",
      "max_amt": "1900000",
      "mst_name": "오사카 4일-1일자유",
      "t_content": "1일자유관광이 가능한 3박4일 상품입니다.",
      "img_seq": "P000164328",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "1일자유관광이 가능한 3박4일 상품입니다.",
      "tour_day": "4",
      "start_dy": "매일",
      "orderSeq": "4"
    },
    {
      "sort_no": "4",
      "pkg_mst_code": "JOP510",
      "sMonth": "201609",
      "min_amt": "599000",
      "max_amt": "2250000",
      "mst_name": "오사카 4일-전일관광",
      "t_content": "간사이 핵심지역을 돌아보는 오사카 3박4일 패키지상품입니다.",
      "img_seq": "P000020712",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "간사이 핵심지역을 돌아보는 오사카 3박4일 패키지상품입니다.",
      "tour_day": "4",
      "start_dy": "매일",
      "orderSeq": "5"
    },
    {
      "sort_no": "5",
      "pkg_mst_code": "JOP515",
      "sMonth": "201609",
      "min_amt": "879000",
      "max_amt": "1950000",
      "mst_name": "오사카 4일-유니버셜 스튜디오(USJ)",
      "t_content": "유니버셜 스튜디오 재팬을 방문하는 3박4일 상품입니다.",
      "img_seq": "P000140906",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "유니버셜 스튜디오 재팬을 방문하는 3박4일 상품입니다.",
      "tour_day": "4",
      "start_dy": "매일",
      "orderSeq": "6"
    },
    {
      "sort_no": "6",
      "pkg_mst_code": "JOP580",
      "sMonth": "201609",
      "min_amt": "1299000",
      "max_amt": "1799000",
      "mst_name": "[4+ 가족여행] 오사카 4일-전일관광",
      "t_content": "우리가족끼리 즐기는 스페셜 단독여행 '4+가족여행'!  역사&문화/관광/쇼핑 등으로 유명한 간사이 지방의 오사카/교토/나라/고베 관광과 일본 3대 온천 중  하나아리마온천 체험까지 관광과 쇼핑을 가족 스케쥴에 맞게 여유롭게 즐기세요.",
      "img_seq": "P000038796",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "우리가족끼리 즐기는 스페셜 단독여행 '4+가족여행'!  역사&문화/관광/...",
      "tour_day": "3~5",
      "start_dy": "매일",
      "orderSeq": "7"
    },
    {
      "sort_no": "7",
      "pkg_mst_code": "JHP500",
      "sMonth": "201609",
      "min_amt": "799000",
      "max_amt": "1699000",
      "mst_name": "오사카/교토(나라)/벳부 4일",
      "t_content": "대형훼리를 타고 혼슈와 온천으로 유명한 규슈까지 연계하여 이동하는 상품입니다.",
      "img_seq": "P000065428",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "대형훼리를 타고 혼슈와 온천으로 유명한 규슈까지 연계하여 이동하는 상품입...",
      "tour_day": "4",
      "start_dy": "매일",
      "orderSeq": ""
    },
    {
      "sort_no": "8",
      "pkg_mst_code": "JHP530",
      "sMonth": "201609",
      "min_amt": "1959000",
      "max_amt": "3069000",
      "mst_name": "신일본일주 4, 5일",
      "t_content": "일본 혼슈의 대표적인 관광지만을 모아 놓은 효율적인 일정입니다. 오사카,교토 & 도쿄, 하코네, 닛코 등 아름다운 자연과 세계문화유산은 물론, 고도로 발전된 일본의 현재와 미래까지 볼 수 있는 다채로운 상품입니다.",
      "img_seq": "P000014319",
      "dy_list": "1,2,3,5,6,7",
      "content": "일본 혼슈의 대표적인 관광지만을 모아 놓은 효율적인 일정입니다. 오사카,...",
      "tour_day": "5",
      "start_dy": "일,월,화,목,금,토",
      "orderSeq": ""
    },
    {
      "sort_no": "9",
      "pkg_mst_code": "JOP503",
      "sMonth": "201609",
      "min_amt": "1399000",
      "max_amt": "1849000",
      "mst_name": "[多드림] 오사카 3일",
      "t_content": "하나투어 고품격 상품인 다드림 2박3일 패키지여행입니다.",
      "img_seq": "P000552447",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "하나투어 고품격 상품인 다드림 2박3일 패키지여행입니다.",
      "tour_day": "3",
      "start_dy": "매일",
      "orderSeq": ""
    },
    {
      "sort_no": "10",
      "pkg_mst_code": "JOP504",
      "sMonth": "201609",
      "min_amt": "600000",
      "max_amt": "1070000",
      "mst_name": "[길라잡이] 오사카 3일-전일자유+ 1일투어",
      "t_content": "",
      "img_seq": "P000020712",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "",
      "tour_day": "3",
      "start_dy": "매일",
      "orderSeq": ""
    },
    {
      "sort_no": "11",
      "pkg_mst_code": "JOP508",
      "sMonth": "201609",
      "min_amt": "1299000",
      "max_amt": "2050000",
      "mst_name": "[多드림]오사카 3일- 유니버셜 스튜디오(USJ)",
      "t_content": "유니버셜 스튜디오 재팬을 방문하는 하나투어 고품격 상품인 다드림 2박3일 상품입니다.",
      "img_seq": "P000593715",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "유니버셜 스튜디오 재팬을 방문하는 하나투어 고품격 상품인 다드림 2박3일...",
      "tour_day": "3",
      "start_dy": "매일",
      "orderSeq": ""
    },
    {
      "sort_no": "12",
      "pkg_mst_code": "JOP512",
      "sMonth": "201609",
      "min_amt": "599000",
      "max_amt": "699000",
      "mst_name": "오사카 4일-2일자유",
      "t_content": "",
      "img_seq": "P000164328",
      "dy_list": "1,2,3,4",
      "content": "",
      "tour_day": "4",
      "start_dy": "일,월,화,수",
      "orderSeq": ""
    },
    {
      "sort_no": "13",
      "pkg_mst_code": "JOP513",
      "sMonth": "201609",
      "min_amt": "1249000",
      "max_amt": "2500000",
      "mst_name": "[多드림] 오사카 4일",
      "t_content": "하나투어 고품격 상품인 다드림 3박4일 패키지여행입니다.",
      "img_seq": "P000552447",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "하나투어 고품격 상품인 다드림 3박4일 패키지여행입니다.",
      "tour_day": "4",
      "start_dy": "매일",
      "orderSeq": ""
    },
    {
      "sort_no": "14",
      "pkg_mst_code": "JOP514",
      "sMonth": "201609",
      "min_amt": "610000",
      "max_amt": "1000000",
      "mst_name": "[길라잡이] 오사카 4일-전일자유 + 1일 투어",
      "t_content": "항공+호텔만 포함되어있는 일반 자유여행 상품과는 차별화 된, 쿠루쿠루 버스 1일투어가 포함된 오사카 세미자유 상품입니다.",
      "img_seq": "P000000097",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "항공+호텔만 포함되어있는 일반 자유여행 상품과는 차별화 된, 쿠루쿠루 버...",
      "tour_day": "4",
      "start_dy": "매일",
      "orderSeq": ""
    },
    {
      "sort_no": "15",
      "pkg_mst_code": "JOP518",
      "sMonth": "201609",
      "min_amt": "1249000",
      "max_amt": "2200000",
      "mst_name": "[多드림]오사카 4일-유니버셜 스튜디오(USJ)",
      "t_content": "유니버셜 스튜디오 재팬을 방문하는 하나투어 고품격 상품인 다드림 3박4일 상품입니다.",
      "img_seq": "P000593802",
      "dy_list": "1,2,3,4,5,6,7",
      "content": "유니버셜 스튜디오 재팬을 방문하는 하나투어 고품격 상품인 다드림 3박4일...",
      "tour_day": "4",
      "start_dy": "매일",
      "orderSeq": ""
    },
    {
      "sort_no": "16",
      "pkg_mst_code": "JYP500",
      "sMonth": "201609",
      "min_amt": "1399000",
      "max_amt": "1399000",
      "mst_name": "요나고/돗토리사구 3일",
      "t_content": "일본 최대의 모래언덕, 돗토리 사구와 다이센산의 멋진 풍경, 그리고 온천욕! 소박하고 깨끗한 일본 온천여행을 즐기실 수 있습니다.",
      "img_seq": "P000114168",
      "dy_list": "5",
      "content": "일본 최대의 모래언덕, 돗토리 사구와 다이센산의 멋진 풍경, 그리고 온천...",
      "tour_day": "3",
      "start_dy": "목",
      "orderSeq": ""
    },
    {
      "sort_no": "17",
      "pkg_mst_code": "JYP545",
      "sMonth": "201609",
      "min_amt": "1399000",
      "max_amt": "1499000",
      "mst_name": "오카야마 4일",
      "t_content": "일본 주고쿠에 위치한 보물같은 관광지 오카아마와 쿠라시키 미관지구를 만나보실 수 있는 상품입니다.",
      "img_seq": "P000682919",
      "dy_list": "5",
      "content": "일본 주고쿠에 위치한 보물같은 관광지 오카아마와 쿠라시키 미관지구를 만나...",
      "tour_day": "3",
      "start_dy": "목",
      "orderSeq": ""
    }
  ]
}